export const siteContent = {
    brand: "Kanha Gupta",
    firstName: "Kanha",
    lastName: "Gupta",
    role: "Full Stack (MERN + GenAI)",
    heroTitle: "I build production-ready web experiences with strong UI, clean APIs, and fast delivery.",
    heroCopy: "Crafting high-performance digital experiences with React.js, Next.js, and Node.js. Specializing in turning complex business logic into seamless, scalable web applications.",
    availability: "Available for Hire",
    location: "India",
    heroLocation: "Bhopal, Indore, MP",
    email: "kanhashree2223@gmail.com",
    phone: "+91 9131395725",
    basedIn: "Madhya Pradesh, India",
    github: "http://github.com/kanha-beep",
    linkedin: "https://www.linkedin.com/in/kanha-gupta-833b10206/",
    // assistantMessage:
    //   "Hi! I'm Kanha's portfolio assistant. I can help you learn about experience, projects, skills, and background.",
    about: "I work across frontend and backend, with a focus on polished interfaces, practical architecture, and shipping real products. I enjoy taking ideas from rough concept to live deployment with attention to performance and detail.",
    journey: "I build production-ready MERN products with clean APIs, scalable auth flows, and polished interfaces, while steadily expanding into GenAI-powered workflows and automation.",
    expertise: [
        "React.js",
        "Node.js",
        "Express.js",
        "MongoDB",
        "Tailwind CSS",
        "REST APIs",
        "Java backend",
        "Python for AI"
    ],
    heroStack: ["MongoDB", "Express", "React.js", "Node.js"],
    skillGroups: [{
            title: "Frontend Development",
            description: "Responsive UI systems, state handling, component architecture, and performance-minded interactions.",
            skills: ["ReactJS", "Typescript", "NextJS", "JavaScript", "Tailwind", "HTML", "CSS"],
        },
        {
            title: "Backend Development",
            description: "Clean API layers, auth flows, server-side logic, and maintainable data models.",
            skills: ["Node.js", "Express", "MongoDB", "Mongoose", "JWT", "JAVA", "Python"],
        },

        {
            title: "AI",
            description: "Integrate AI ML for seamless operation",
            skills: [
                "Generative AI",
                "LangChain",
                "Prompt Engineering",
                "Retrieval-Augmented Generation (RAG)",
                "LLM Application Development",
                "AI Agent Development",
                "Vector Databases",
                "Embedding Models",
            ]
        },
        {
            title: "Workflow",
            description: "Project delivery with version control, debugging discipline, and practical deployment habits.",
            skills: ["Git", "Postman", "Vercel", "Render", "Kubernet", "Docker", "CI/CD"],
        }
    ],
    highlights: [
        { value: "03+", label: "Featured SaaS Builds" },
        { value: "02", label: "Work Experiences" },
        { value: "MERN + AI", label: "Primary Focus" },
    ],
    experiences: [{
            role: "Full Stack Web Developer",
            company: "EazyBytes",
            period: "Dec 2025 - Jan 2026",
            location: "India",
            accent: "blue",
            points: [
                "Section Hide/Unhide for effective learning.",
                "Search bar to quickly search the relevant topics.",
                "Properly segregated sections for proper understanding.",
            ],
        },
        {
            role: "Full Stack Web Developer",
            company: "InLignTech",
            period: "Sep 2025 - Nov 2025",
            location: "India",
            accent: "violet",
            points: [
                "Built a multi-tenant notes SaaS with RBAC and REST APIs, enabling scalable and isolated user workflows.",
                "Developed a task management and analytics dashboard with assignment and tracking flows that improved engagement and reduced manual coordination.",
                "Optimized task updates, comments, and request workflows to improve completion rate and overall platform usage.",
            ],
        },
    ],
    educationCards: [{
            title: "BCA / Bachelor of Computer Applications",
            year: "College",
            institution: "Motilal Nehru College, Delhi University",
            note: "Focused on computer applications, programming fundamentals, databases, and web development.",
            badge: "UG",
            iconClass: "fa-solid fa-graduation-cap",
            accent: "blue",
        },
        {
            title: "Data Analyst Program",
            year: "Ongoing",
            institution: "BITS Pilani",
            note: "Currently building stronger skills in analytics, data interpretation, visualization, and business-focused problem solving.",
            badge: "Program",
            iconClass: "fa-solid fa-chart-column",
            accent: "gold",
        },
        {
            title: "Class XII",
            year: "Schooling",
            institution: "St Joseph's Co-Ed School",
            note: "Completed higher secondary education with a strong academic base before moving into technology-focused studies.",
            badge: "Higher Secondary",
            iconClass: "fa-solid fa-book-open",
            accent: "blue",
        },
        {
            title: "Class X",
            year: "Schooling",
            institution: "St Joseph's Co-Ed School",
            note: "Built the academic foundation that shaped later interest in computers, analysis, and technical learning.",
            badge: "Secondary",
            iconClass: "fa-solid fa-school",
            accent: "violet",
        },
    ],
    timeline: [{
            period: "Now",
            title: "Full Stack Development",
            copy: "Building portfolio projects, dashboards, content systems, and polished frontend experiences.",
        },
        {
            period: "Recent",
            title: "MERN Stack Practice",
            copy: "Working on complete applications with authentication, CRUD workflows, admin panels, and deployment.",
        },
        {
            period: "Ongoing",
            title: "Skill Growth",
            copy: "Improving DSA, backend design, and production-level frontend motion and accessibility.",
        },
    ],
    profileImage: "https://res.cloudinary.com/dw7elrwuy/image/upload/v1783575081/uploads/s7t11e0smopunugm3dq2.jpg",
    aboutImage: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1200&q=80",
};